sonar.host.url=http://localhost:9000
sonar.token=sqa_a46b351db577379ce23d6baa0b9be04210b3bc22

sonar.projectKey=assignment_submission_system_fe
sonar.projectName=Assignment Submission System FE
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**, **/dist/**, **/*.test.js